[package]
name = "diskgrep"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
libc = "0.2.174"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
